agent_models:
  bill_ackman:
    default_model: gpt-4o
    default_provider: OpenAI
  michael_burry:
    default_model: gpt-4o
    default_provider: OpenAI
  portfolio_manager:
    default_model: gpt-4o
    default_provider: OpenAI
  rakesh_jhunjhunwala:
    default_model: gpt-4o
    default_provider: OpenAI

data_providers:
  available:
    financial_datasets:
      api_key_env: FINANCIAL_DATASETS_API_KEY
      name: FinancialDatasets.ai
    tushare:
      api_key_env: TUSHARE_API_KEY
      name: Tushare Pro
  default: financial_datasets

interfaces:
  call_llm_deepseek:
    cache_key_components:
    - prompt
    - model_name
    - pydantic_model
    - agent_name
    cache_layers:
    - persistent
    cache_type: llm_responses
    models:
    - deepseek-reasoner
    - deepseek-chat
    - deepseek-*
    providers:
    - DeepSeek
    timeout:
      timeout_seconds: 30
      max_retries: 3
      retry_delay_factor: 0.1
    ttl:
      default: 86400
  call_llm_other:
    cache_layers: []
    cache_type: none
    providers:
    - OpenAI
    - Anthropic
    - Gemini
    - Groq
    - Ollama
    timeout:
      timeout_seconds: 30
      max_retries: 3
      retry_delay_factor: 0.1
    ttl:
      default: 0
  get_company_news:
    cache_layers:
    - memory
    - persistent
    cache_type: company_news
    merge_key: date
    timeout:
      timeout_seconds: 5
      max_retries: 3
      retry_delay_factor: 0.5
    ttl:
      default: 86400
  get_financial_metrics:
    cache_layers:
    - memory
    - persistent
    cache_type: financial_metrics
    merge_key: report_period
    timeout:
      timeout_seconds: 5
      max_retries: 3
      retry_delay_factor: 0.5
    ttl:
      default: 86400
  get_insider_trades:
    cache_layers:
    - memory
    - persistent
    cache_type: insider_trades
    merge_key: filing_date
    timeout:
      timeout_seconds: 5
      max_retries: 3
      retry_delay_factor: 0.5
    ttl:
      default: 86400
  get_prices:
    cache_layers:
    - memory
    - persistent
    cache_type: prices
    merge_key: time
    timeout:
      timeout_seconds: 5
      max_retries: 3
      retry_delay_factor: 0.5
    ttl:
      after_hours: 86400
      market_hours: 3600
  search_line_items:
    cache_layers:
    - memory
    - persistent
    cache_type: line_items
    merge_key: report_period
    timeout:
      timeout_seconds: 5
      max_retries: 3
      retry_delay_factor: 0.5
    ttl:
      default: 86400
